DROP DATABASE IF EXISTS DAWBANK;
CREATE DATABASE DAWBANK;
USE DAWBANK;

-- Crear la tabla CUENTABANCARIA
CREATE TABLE CUENTABANCARIA(
    IBAN VARCHAR(24) PRIMARY KEY,
    TITULAR VARCHAR(40) NOT NULL UNIQUE,
    SALDO DECIMAL(8,2) DEFAULT 0.00
);

-- Crear la tabla MOVIMIENTOS
CREATE TABLE MOVIMIENTOS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IBAN VARCHAR(24),
    TITULAR VARCHAR(40) NOT NULL,
    FECHA DATE,
    CANTIDAD DECIMAL(8,2),
    TIPO ENUM('INGRESO', 'RETIRADA'),
    FOREIGN KEY (IBAN) REFERENCES CUENTABANCARIA(IBAN)
);



-- Crear la vista VISTA_SALDO
CREATE VIEW VISTA_SALDO AS 
SELECT 
    C.IBAN,
    C.TITULAR,
    COALESCE(SUM(CASE WHEN M.TIPO = 'INGRESO' THEN M.CANTIDAD ELSE 0 END), 0) - 
    COALESCE(SUM(CASE WHEN M.TIPO = 'RETIRADA' THEN M.CANTIDAD ELSE 0 END), 0) AS SALDO
FROM 
    CUENTABANCARIA C
LEFT JOIN 
    MOVIMIENTOS M ON C.IBAN = M.IBAN
GROUP BY 
    C.IBAN, C.TITULAR;

-- Inserción de datos en la tabla CUENTABANCARIA
INSERT INTO CUENTABANCARIA (IBAN, TITULAR, SALDO)
VALUES ('ES1234567891012131415167', 'PEDRO SALAZAR', SALDO);

-- Inserción de datos en la tabla MOVIMIENTOS
INSERT INTO MOVIMIENTOS (IBAN, TITULAR, FECHA, CANTIDAD, TIPO)
VALUES
    ('ES1234567891012131415167', 'PEDRO SALAZAR', '2023-10-01', 100.00, 'INGRESO'),
    ('ES1234567891012131415167', 'PEDRO SALAZAR', '2023-10-05', 50.00, 'RETIRADA');
