DROP DATABASE IF EXISTS DAWBANK;
CREATE DATABASE DAWBANK;
USE DAWBANK;

-- Crear la tabla CUENTABANCARIA
CREATE TABLE CUENTABANCARIA(
    IBAN VARCHAR(24) PRIMARY KEY,
    TITULAR VARCHAR(40) NOT NULL UNIQUE,
    SALDO DECIMAL(8,2) DEFAULT 0.00
);

-- Crear la tabla MOVIMIENTOS
CREATE TABLE MOVIMIENTOS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IBAN VARCHAR(24),
    FECHA DATE,
    CANTIDAD DECIMAL(8,2),
    TIPO ENUM('INGRESO', 'RETIRADA'),
    FOREIGN KEY (IBAN) REFERENCES CUENTABANCARIA(IBAN)
);

-- Inserción de datos en la tabla CUENTABANCARIA
INSERT INTO CUENTABANCARIA (IBAN, TITULAR, SALDO) 
VALUES ('ES1234567891012131415167', 'PEDRO SALAZAR', 50);

-- Inserción de datos en la tabla MOVIMIENTOS
INSERT INTO MOVIMIENTOS (IBAN, FECHA, CANTIDAD, TIPO)  
VALUES 
    ('ES1234567891012131415167', '2023-10-01', 100.00, 'INGRESO'),
    ('ES1234567891012131415167', '2023-10-05', 50.00, 'RETIRADA');

-- Consulta para calcular el saldo restante
SELECT 
    C.IBAN,
    C.SALDO + COALESCE(SUM(CASE WHEN M.TIPO = 'INGRESO' THEN M.CANTIDAD ELSE 0 END), 0) - 
    COALESCE(SUM(CASE WHEN M.TIPO = 'RETIRADA' THEN M.CANTIDAD ELSE 0 END), 0) AS SALDO_RESTANTE
FROM 
    CUENTABANCARIA C
LEFT JOIN 
    MOVIMIENTOS M ON C.IBAN = M.IBAN
GROUP BY 
    C.IBAN;
SELECT * FROM CUENTABANCARIA;
SELECT * FROM MOVIMIENTOS;
-- grant select to dawbank.movimientos for root;DROP DATABASE IF EXISTS DAWBANK;
CREATE DATABASE DAWBANK;
USE DAWBANK;

-- Crear la tabla CUENTABANCARIA
CREATE TABLE CUENTABANCARIA(
    IBAN VARCHAR(24) PRIMARY KEY,
    TITULAR VARCHAR(40) NOT NULL UNIQUE,
    SALDO DECIMAL(8,2) DEFAULT 0.00
);

-- Crear la tabla MOVIMIENTOS
CREATE TABLE MOVIMIENTOS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IBAN VARCHAR(24),
    FECHA DATE,
    CANTIDAD DECIMAL(8,2),
    TIPO ENUM('INGRESO', 'RETIRADA'),
    FOREIGN KEY (IBAN) REFERENCES CUENTABANCARIA(IBAN)
);

-- Inserción de datos en la tabla CUENTABANCARIA
INSERT INTO CUENTABANCARIA (IBAN, TITULAR, SALDO) 
VALUES ('ES1234567891012131415167', 'PEDRO SALAZAR', 50);

-- Inserción de datos en la tabla MOVIMIENTOS
INSERT INTO MOVIMIENTOS (IBAN, FECHA, CANTIDAD, TIPO)  
VALUES 
    ('ES1234567891012131415167', '2023-10-01', 100.00, 'INGRESO'),
    ('ES1234567891012131415167', '2023-10-05', 50.00, 'RETIRADA');

-- Consulta para calcular el saldo restante
SELECT 
    C.IBAN,
    C.SALDO + COALESCE(SUM(CASE WHEN M.TIPO = 'INGRESO' THEN M.CANTIDAD ELSE 0 END), 0) - 
    COALESCE(SUM(CASE WHEN M.TIPO = 'RETIRADA' THEN M.CANTIDAD ELSE 0 END), 0) AS SALDO_RESTANTE
FROM 
    CUENTABANCARIA C
LEFT JOIN 
    MOVIMIENTOS M ON C.IBAN = M.IBAN
GROUP BY 
    C.IBAN;
SELECT * FROM CUENTABANCARIA;
SELECT * FROM MOVIMIENTOS;
-- grant select to dawbank.movimientos for root;
